# cop configuration for Metrics should be found here
#
# Assignment Branch Complexity increasing slightly from the default of 15
Metrics/AbcSize:
  Max: 18

# Ideally this would be 5 or 6
Metrics/MethodLength:
  Max: 15

# No need to run this on rake tasks
Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - config/routes.rb
    - lib/tasks/*.rake
    - spec/**/*.rb

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 116

# don't count kwargs in paramlist
Metrics/ParameterLists:
  CountKeywordArgs: false
