# Cop configuration for rubocop-security here

# this dictates the use of capy aliases to typical rspec methods
# https://rubocop.readthedocs.io/projects/rspec/en/read-the-docs/cops_capybara/#capybarafeaturemethods
RSpec/Capybara/FeatureMethods:
  Enabled: false

# This sets the default behavior of ToNot
RSpec/NotToNot:
  Enabled: true
  EnforcedStyle: "to_not"

# align left braces for lets etc
RSpec/AlignLeftLetBrace:
  Enabled: true

